import json
from contextlib import contextmanager
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row

from monitor.state import evaluate


class PostgresIncidentStore:
    def __init__(self, database_url):
        if not database_url:
            raise ValueError("DATABASE_URL is required")

        self.database_url = database_url

        with self.connect() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS monitor_state (
                    id INTEGER PRIMARY KEY CHECK (id = 1),
                    consecutive_failures INTEGER NOT NULL DEFAULT 0,
                    incident_open INTEGER NOT NULL DEFAULT 0
                )
            """)

            conn.execute("""
                CREATE TABLE IF NOT EXISTS incidents (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    opened_at TEXT NOT NULL,
                    recovered_at TEXT,
                    duration_seconds DOUBLE PRECISION
                )
            """)

            conn.execute("""
                CREATE TABLE IF NOT EXISTS notifications (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    incident_id BIGINT NOT NULL REFERENCES incidents(id),
                    event TEXT NOT NULL,
                    payload TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'pending',
                    attempts INTEGER NOT NULL DEFAULT 0,
                    last_error TEXT,
                    delivered_at TEXT,
                    UNIQUE (incident_id, event)
                )
            """)

            conn.execute("""
                CREATE TABLE IF NOT EXISTS check_results (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    checked_at TEXT NOT NULL,
                    healthy INTEGER NOT NULL,
                    status_code INTEGER,
                    latency_ms DOUBLE PRECISION NOT NULL,
                    error TEXT
                )
            """)

            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_check_results_checked_at
                ON check_results (checked_at)
            """)

            conn.execute("""
                INSERT INTO monitor_state
                    (id, consecutive_failures, incident_open)
                VALUES (1, 0, 0)
                ON CONFLICT (id) DO NOTHING
            """)

    @contextmanager
    def connect(self):
        with psycopg.connect(
            self.database_url,
            row_factory=dict_row,
            connect_timeout=10,
        ) as conn:
            yield conn

    def load_state(self):
        with self.connect() as conn:
            row = conn.execute("""
                SELECT consecutive_failures, incident_open
                FROM monitor_state
                WHERE id = 1
            """).fetchone()

        if row is None:
            raise RuntimeError("Monitoring state is missing")

        return {
            "consecutive_failures": row["consecutive_failures"],
            "incident_open": bool(row["incident_open"]),
        }

    def record(self, result, threshold=2):
        with self.connect() as conn:

            # Serialize state transitions across concurrent processes.
            row = conn.execute("""
                SELECT consecutive_failures, incident_open
                FROM monitor_state
                WHERE id = 1
                FOR UPDATE
            """).fetchone()

            if row is None:
                raise RuntimeError("Monitoring state is missing")

            state = {
                "consecutive_failures": row["consecutive_failures"],
                "incident_open": bool(row["incident_open"]),
            }

            new_state, event = evaluate(
                state,
                result,
                threshold,
            )

            timestamp = result["timestamp"]

            conn.execute("""
                INSERT INTO check_results
                    (checked_at, healthy, status_code, latency_ms, error)
                VALUES (%s, %s, %s, %s, %s)
            """, (
                timestamp,
                int(result["healthy"]),
                result["status_code"],
                result["latency_ms"],
                result["error"],
            ))

            if event == "INCIDENT_OPENED":
                incident = conn.execute("""
                    INSERT INTO incidents (opened_at)
                    VALUES (%s)
                    RETURNING id
                """, (timestamp,)).fetchone()

                incident_id = incident["id"]

                payload = {
                    "event": "INCIDENT_OPENED",
                    "incident_id": incident_id,
                    "timestamp": timestamp,
                    "message": "Application health check failed",
                }

                conn.execute("""
                    INSERT INTO notifications
                        (incident_id, event, payload)
                    VALUES (%s, %s, %s)
                """, (
                    incident_id,
                    event,
                    json.dumps(payload),
                ))

            elif event == "RECOVERED":
                incident = conn.execute("""
                    SELECT id, opened_at
                    FROM incidents
                    WHERE recovered_at IS NULL
                    ORDER BY id DESC
                    LIMIT 1
                    FOR UPDATE
                """).fetchone()

                if incident is None:
                    raise RuntimeError(
                        "Recovery detected without an open incident"
                    )

                opened = datetime.fromisoformat(
                    incident["opened_at"]
                )

                recovered = datetime.fromisoformat(timestamp)

                duration = max(
                    0.0,
                    round(
                        (recovered - opened).total_seconds(),
                        3,
                    ),
                )

                conn.execute("""
                    UPDATE incidents
                    SET recovered_at = %s,
                        duration_seconds = %s
                    WHERE id = %s
                """, (
                    timestamp,
                    duration,
                    incident["id"],
                ))

                payload = {
                    "event": "RECOVERED",
                    "incident_id": incident["id"],
                    "timestamp": timestamp,
                    "duration_seconds": duration,
                    "message": "Application health restored",
                }

                conn.execute("""
                    INSERT INTO notifications
                        (incident_id, event, payload)
                    VALUES (%s, %s, %s)
                """, (
                    incident["id"],
                    event,
                    json.dumps(payload),
                ))

            conn.execute("""
                UPDATE monitor_state
                SET consecutive_failures = %s,
                    incident_open = %s
                WHERE id = 1
            """, (
                new_state["consecutive_failures"],
                int(new_state["incident_open"]),
            ))

        return new_state, event

    def recent_checks(self, limit=100):
        if limit < 1 or limit > 10000:
            raise ValueError("limit must be between 1 and 10000")
        with self.connect() as conn:
            rows = conn.execute("""
                SELECT checked_at, healthy, status_code,
                       latency_ms, error
                FROM check_results
                ORDER BY id DESC
                LIMIT %s
            """, (limit,)).fetchall()
        return [dict(row) for row in rows]

    def list_incidents(self):
        with self.connect() as conn:
            rows = conn.execute("""
                SELECT id, opened_at, recovered_at,
                       duration_seconds
                FROM incidents
                ORDER BY id
            """).fetchall()

        return rows

    def pending_notifications(self):
        with self.connect() as conn:
            rows = conn.execute("""
                SELECT id, incident_id, event, payload,
                       status, attempts, last_error,
                       delivered_at
                FROM notifications
                WHERE status = 'pending'
                ORDER BY id
            """).fetchall()

        return rows

    def mark_delivered(self, notification_id):
        timestamp = datetime.now(timezone.utc).isoformat()

        with self.connect() as conn:
            cursor = conn.execute("""
                UPDATE notifications
                SET status = 'delivered',
                    delivered_at = %s,
                    last_error = NULL,
                    attempts = attempts + 1
                WHERE id = %s
                  AND status = 'pending'
            """, (
                timestamp,
                notification_id,
            ))

            return cursor.rowcount == 1

    def mark_failed(self, notification_id, error):
        with self.connect() as conn:
            cursor = conn.execute("""
                UPDATE notifications
                SET attempts = attempts + 1,
                    last_error = %s
                WHERE id = %s
                  AND status = 'pending'
            """, (
                str(error)[:500],
                notification_id,
            ))

            return cursor.rowcount == 1